/**
 * Machine-readable reason codes for risk signals.
 */
const ReasonCodes = {
  ALLOWLIST_POOL: "ALLOWLIST_POOL",
  ALLOWLIST_TOKENS: "ALLOWLIST_TOKENS",
  SWAP_LARGE: "SWAP_LARGE",
  SWAP_MICRO: "SWAP_MICRO",
  THREAT_MALICIOUS: "THREAT_MALICIOUS",
  THREAT_KNOWN_DRAINER: "THREAT_KNOWN_DRAINER",
  THREAT_KNOWN_PHISHING: "THREAT_KNOWN_PHISHING",
  THREAT_TORNADO: "THREAT_TORNADO",
  THREAT_HONEYPOT: "THREAT_HONEYPOT",
  THREAT_TRADING_RESTRICTED: "THREAT_TRADING_RESTRICTED",
  THREAT_TAX: "THREAT_TAX",
  THREAT_OWNER_CHANGE: "THREAT_OWNER_CHANGE",
  THREAT_NOT_OPEN_SOURCE: "THREAT_NOT_OPEN_SOURCE",
  THREAT_PROXY: "THREAT_PROXY",
  THREAT_MINTABLE: "THREAT_MINTABLE",
  THREAT_BURNABLE: "THREAT_BURNABLE",
  ONCHAIN_SENTINEL: "ONCHAIN_SENTINEL",
  ONCHAIN_EOA: "ONCHAIN_EOA",
  ONCHAIN_SMALL_BYTECODE: "ONCHAIN_SMALL_BYTECODE",
  ONCHAIN_FRESH: "ONCHAIN_FRESH",
  ONCHAIN_FRESH_PREFUNDED: "ONCHAIN_FRESH_PREFUNDED",
  ONCHAIN_LOW_TX: "ONCHAIN_LOW_TX",
  ONCHAIN_ESTABLISHED: "ONCHAIN_ESTABLISHED",
  ONCHAIN_LARGE_ETH_BALANCE: "ONCHAIN_LARGE_ETH_BALANCE",
  BYTECODE_SELFDESTRUCT: "BYTECODE_SELFDESTRUCT",
  BYTECODE_DELEGATECALL: "BYTECODE_DELEGATECALL",
  BYTECODE_MINIMAL_PROXY: "BYTECODE_MINIMAL_PROXY",
  BYTECODE_LARGE: "BYTECODE_LARGE",
};

module.exports = { ReasonCodes };
