/**
 * Machine-readable reason codes for risk signals.
 */
const ReasonCodes = {
  ALLOWLIST_POOL: "ALLOWLIST_POOL",
  ALLOWLIST_TOKENS: "ALLOWLIST_TOKENS",
  SWAP_LARGE: "SWAP_LARGE",
  SWAP_MICRO: "SWAP_MICRO",
  THREAT_MALICIOUS: "THREAT_MALICIOUS",
  THREAT_HONEYPOT: "THREAT_HONEYPOT",
  THREAT_TAX: "THREAT_TAX",
  THREAT_OWNER_CHANGE: "THREAT_OWNER_CHANGE",
  ONCHAIN_EOA: "ONCHAIN_EOA",
  ONCHAIN_SMALL_BYTECODE: "ONCHAIN_SMALL_BYTECODE",
  ONCHAIN_FRESH: "ONCHAIN_FRESH",
  ONCHAIN_LOW_TX: "ONCHAIN_LOW_TX",
  ONCHAIN_ESTABLISHED: "ONCHAIN_ESTABLISHED",
  BYTECODE_SELFDESTRUCT: "BYTECODE_SELFDESTRUCT",
  BYTECODE_DELEGATECALL: "BYTECODE_DELEGATECALL",
  BYTECODE_MINIMAL_PROXY: "BYTECODE_MINIMAL_PROXY",
  BYTECODE_LARGE: "BYTECODE_LARGE",
};

module.exports = { ReasonCodes };
